services:
  - type: worker
    name: lead-scalper-bot
    runtime: python
    buildWith: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    # ADD THIS LINE: It prevents Render from spinning up a 'twin'
    numInstances: 1 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_ID
        sync: false
      - key: SOLANA_PRIVATE_KEY
        sync: false
      - key: HELIUS_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK
        sync: false
      - key: DATABASE_URL
        sync: false
